name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - main  # Deploy only when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.1'

    - name: Install dependencies
      run: npm i

    - name: Build the Next.js application
      run: npm run build

    - name: Archive production artifacts
      run: zip -r build.zip .next static package.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build.zip

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > ec2-key.pem
        chmod 600 ec2-key.pem
        scp -i ec2-key.pem -o StrictHostKeyChecking=no build/build.zip $EC2_USER@$EC2_HOST:~/build.zip
        ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          unzip -o ~/build.zip -d ~/Helloworld-Nextjs/
          cd ~/Helloworld-Nextjs
          npm i
          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- run dev
        EOF
